language: node_js
node_js:
   - “8.1.3”

branches:
   only:
      - rch

before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

after_success:
   - firebase deploy --token 1/XQIPsCTl3fm2mvMhb84f3O5h5hbJ_jhgkGupv2Srzlo
